Repository mighty-paws/Petstagram, pull requests merged in 2023-04, with the labels that each got.

#9 Fix/all nextjs 새로고침 시 css가 초기화 되는 문제 해결
  .babelrc
  .babelsrc
  package-lock.json
  package.json
Labels: 🐞 BugFix

#28 Feat 메인페이지 마크업 완성
  package-lock.json
  package.json
  src/components/ImageSwiper/ImageSwiper.tsx
  src/components/PostCard/PostCard.tsx
  src/components/RecommendFollow/FollowList.tsx
  src/components/RecommendFollow/RecommendFollow.tsx
  src/components/RecommendFollow/UserList.tsx
  src/components/index.ts
  src/pages/main.tsx
Labels: ✨ Feature

#39 feat: ImageSwiper에 스타일 추가할 수 있도록 변경(#38)
  src/components/ImageSwiper/ImageSwiper.tsx
Labels: ✨ Feature

#41 style: 비밀번호 찾기,프로필 편집 디자인 완성 (#34)
  src/components/editprofile/Edit.tsx
  src/components/editprofile/EditPassword.tsx
  src/components/editprofile/EditProfile.tsx
  src/pages/passwordreset.tsx
  src/public/images/security.svg
Labels: 🎨 Html&css, 🥰 Accessibility
