Repository mighty-paws/Petstagram, pull requests merged in 2023-05, with the labels that each got.

#45 [Fix] ImageSwiper 드래그 전체선택 방지
  src/components/ImageSwiper/ImageSwiper.tsx
Labels: 🐞 BugFix

#42 로그인 , 회원가입 페이지 오류메세지 alert 지우고 p태그로 변경
  src/components/editprofile/EditProfile.tsx
  src/pages/login.tsx
  src/pages/passwordreset.tsx
  src/pages/register.tsx
Labels: ✨ Feature, 🥰 Accessibility

#46 feat: 게시물 데이터 불러와서 화면에 렌더링
  next.config.cjs
  package-lock.json
  package.json
  src/components/InfiniteScroll/InfiniteScroll.tsx
  src/components/InfiniteScroll/UploadData.tsx
  src/components/InfiniteScroll/postList.ts
  src/components/PostCard/PostCard.tsx
  src/components/index.ts
  src/firebase/utils.ts
  src/pages/main.tsx
  src/redux/store.ts
  src/redux/userData.ts
Labels: ✨ Feature

#48 feat: 팔로잉 추천목록 구현
  src/components/InfiniteScroll/InfiniteScroll.tsx
  src/components/InfiniteScroll/UploadData.tsx
  src/components/InfiniteScroll/postList.ts
  src/components/RecommendFollow/FollowList.tsx
  src/components/RecommendFollow/RecommendFollow.tsx
  src/components/RecommendFollow/UserList.tsx
  src/pages/main.tsx
  src/types/data.ts
  src/types/index.ts
  src/types/redux.ts
Labels: ✨ Feature

#51 feat: token 및 util함수 추가(#50)
  src/pages/main.tsx
  src/theme/tokens.js
  src/theme/utils.js
Labels: ⚙ Setting, ✨ Feature

#52 feat: 게시물 카드 css 및 반응형 작업
  public/next.png
  public/prev.png
  src/components/ImageSwiper/ImageSwiper.tsx
  src/components/InfiniteScroll/postList.ts
  src/components/PostCard/Comment/AddComment.tsx
  src/components/PostCard/Comment/DetailCommentUnit.tsx
  src/components/PostCard/Comment/SimpleCommentUnit.tsx
  src/components/PostCard/LikeList.tsx
  src/components/PostCard/PostCard.styled.tsx
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/PostHeader.tsx
  src/components/PostCard/PostIcon.tsx
  src/components/index.ts
  src/pages/_app.tsx
  src/public/icons/PostCard/bookmark.png
  src/public/icons/PostCard/comment.png
  src/public/icons/PostCard/heart.png
  src/public/icons/PostCard/imoge.svg
  src/public/icons/PostCard/moreVertical.png
  src/public/icons/PostCard/send.png
  src/utils/mainUtil.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#54 feat: 팔로우 추천목록 css
  src/components/RecommendFollow/FollowList.tsx
  src/components/RecommendFollow/RecommendFollow.tsx
  src/components/RecommendFollow/UserList.tsx
  src/pages/main.tsx
Labels: 🎨 Html&css

#56 feat: 메뉴바 구현
  src/components/InfiniteScroll/InfiniteScroll.tsx
  src/components/MenuBar/BubbleMenu/BubbleMenu.tsx
  src/components/MenuBar/MenuBar.tsx
  src/components/PostCard/PostCard.styled.tsx
  src/components/RecommendFollow/FollowList.tsx
  src/components/RecommendFollow/RecommendFollow.tsx
  src/components/editprofile/Edit.tsx
  src/components/index.ts
  src/components/layout/MenuBarLayout.tsx
  src/components/loginCheck.tsx
  src/pages/_app.tsx
  src/pages/main.tsx
  src/pages/setting.tsx
  src/pages/test.tsx
  src/public/icons/MenuBar/Bubble/bookMark.png
  src/public/icons/MenuBar/Bubble/lightMode.png
  src/public/icons/MenuBar/Bubble/settings.png
  src/public/icons/MenuBar/alert-empty.png
  src/public/icons/MenuBar/home-empty.png
  src/public/icons/MenuBar/home-fill.png
  src/public/icons/MenuBar/menuBurger.png
  src/public/icons/MenuBar/message-empty.png
  src/public/icons/MenuBar/message-fill.png
  src/public/icons/MenuBar/post-empty.png
  src/public/icons/MenuBar/search-empty.png
  src/public/icons/MenuBar/search-fill.png
  src/public/icons/MenuBar/settings-empty.png
  src/public/icons/MenuBar/settings-fill.png
  src/public/images/logo-tablet.svg
Labels: ✨ Feature, 🎨 Html&css

#62 modify: data type 정리(#61)
  src/types/data.ts
Labels: ✨ Feature
